included:
  - Sources
  - Tests

excluded:
  - .build
  - AudioWhisper.app
  - Sources/Resources

opt_in_rules:
  - empty_count
  - fatal_error_message
  - toggle_bool

analyzer_rules:
  - unused_import
  - unused_declaration

line_length:
  warning: 130
  error: 160
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 250
  error: 320

file_length:
  warning: 600
  error: 900

cyclomatic_complexity:
  warning: 15
  error: 25

identifier_name:
  min_length: 2
  excluded:
    - id
    - ok
    - to
    - on
    - up
    - ui
    - os
    - ml
    - db
    - vc
    - qr
    - ip

type_name:
  max_length: 60

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

nesting:
  type_level: 3
  statement_level: 5

reporter: "xcode"
